# Generated by Django 5.1.5 on 2025-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('problem_domain', models.CharField(max_length=200)),
                ('problem_statement_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_entry_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=300)),
                ('college_name', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=30)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
    ]
